version: '3'
services:
  # Your app container
  app:
    build: .

  # MySQL database container
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    ports:
      - "33060:3306"
