name: A workflow for my Hello World App

permissions:
  contents: write

on:
  push:
    branches:
      - master
      - develop

jobs:

  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./target/site/jacoco
          flags: Unit Tests
          verbose: true


  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Run Integration Tests
        run: |
          docker compose up -d db
          mvn -Dtest=com.napier.sem.AppIntegrationTest test

      - name: Shutdown Docker
        run: docker compose down

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true


  BuildAndDeploy:
    name: Build and Deploy Using docker-compose
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Package and Run Docker Compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./target/site/jacoco
          flags: BuildAndDeploy
          verbose: true

      - name: Deploy Release to GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/sem.jar


  # build:
  #   name: Hello world action
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Setup network
  #       run: |
  #         docker network create --driver bridge se-methods
  #         docker pull mongo
  #         docker run -d --name mongo-dbserver --network se-methods mongo

  #     - name: Build with Maven
  #       run: mvn package

  #     - name: Build Docker Image
  #       run: docker build -t se_methods .

  #     - name: Run Docker Container
  #       run: docker run --network se-methods --name semcontainer se_methods

  #     - name: View logs
  #       run: docker logs semcontainer
